### ISSUE TITLE
Separate Decentraleyes and definition

### ISSUE THREAD

**Issue by ghost** [Synzvato/decentraleyes#127] opened 2016-11-05 01:13 UTC
You don't have to update Decentraleyes.
All you have to do is create two add-ons as core.
Deyes-firefox
Deyes-palemoon

then, distribute "definition" file, like "Adblock Subscription".

Decentraleyes Settings

Update Interval
Every: [ pulldown menu ][V]
manually
Daily
Weekly
Monthly

Subscription
[X] Main definition by Synzvato
[_] Fetch custom definition...
One URL per line: [
http://localhost/aaaa/bbb.xml
http://localhost/aaaa/bbb2.xml
]

**Comment by GitHubHatesTor** [comment] 2016-11-05 01:14
http://localhost/aaaa/bbb.xml or http://localhost/aaaa/bbb.zip

xml ... contain 1 file
zip ... can contain multiple files

**Comment by GitHubHatesTor** [comment] 2016-11-05 01:18
Good:
Other people can share their work on XML or ZIP file format, for other add-on users(if they have webserver)
Busy @Synzvato don't need to update addon itself(because definition is distributed by update)

Bad:
Connect to the internet. Make sure this addon NEVER send user's information, such as Firefox version number or add-on version number. All HTTP/S requests must only use "GET" request, and never send ANY parameters. Also, the request SHOULD use firefox's default UA.

OK: GET http://localhost/aaaa/bbb.xml Mozilla/5.0 (......
NG: GET http://localhost/aaaa/bbb.xml?platform=x32&addonvar=1.2&... DECENTUPDATER/1.0

**Comment by GitHubHatesTor** [comment] 2016-11-05 01:19
Try "uBlock Origin" add-on and look at "3rd party filter" section.

**Comment by Synzvato** [comment] 2017-11-21 21:11
Thank you very much for sharing your ideas! I will be marking this as a duplicate of related issue #6, in order to keep everything in one place. Please do have a look at it, and feel free to weigh in.

**Closed by Synzvato** 2017-11-21 21:11 UTC
