### ISSUE TITLE
Decentraleyes potentially breaks WU forecasts

### ISSUE THREAD

**Issue by sphh** [Synzvato/decentraleyes#136] opened 2017-01-05 21:17 UTC
I believe that Decentraleyes breaks the 10 day forecast on Weather Underground www.wunderground.com, e.g. [New York Forecast](https://www.wunderground.com/us/ny/new-york/zmw:10001.11.99999): The graphs in the 10-Day Forecast do not get updated, if the page is re-visited at a later time.

Any ideas how I can get it working again? Thanks.

Stephan

**Comment by TriMoon** [comment] 2017-01-10 14:55
Open the log window of Decentraleyes and/or developer tools network panel to see if something is being blocked.
Unfortunately i'm not interested atm to check the sites you linked to as i have no need for them.
Perhaps someone else has more time.

**Comment by Gitoffthelawn** [comment] 2017-01-10 20:21
@TriMoon Does Decentraleyes have a dedicated log window?

**Comment by TriMoon** [comment] 2017-01-11 11:07
Oops, it does not i believe, my mind was on uMatrix :rofl: 
Anyway there are other ways to see if things are blocked as mentioned.

But anyway Decentraleyes is not a filter, it's a script cache in very simple terms.
Thus if a site works with Decentraleyes disabled and breaks when it's enabled, then maybe Decentraleyes is feeding the wrong script for that site.

You can debug that by disabling Decentraleyes and checking which scripts are accessed in the network tab of the developer tools of firefox.
I doubt however that it is providing/feeding a wrong script though, but who knows...
Most probably it's an issue in the logic of the site using the scripts...

**Comment by Synzvato** [comment] 2017-01-27 10:29
@sphh Thanks for sharing your concerns. Appreciated! However, I have tested the forecast screen, extensively and was unable to reproduce your issue. No scripts failed to inject. Did you mean that their graph does not update in the background when leaving the tab open, _or_ when reloading the page?

@TriMoon @Gitoffthelawn Thank you for brainstorming on this. I'm also quite sure Decentraleyes is indeed injecting the correct versions of the requested libraries. Once I have more information on how to reproduce the issue, I could start cooking up a couple of basic experiments.

**Comment by sphh** [comment] 2017-01-27 13:51
@Synzvato Thanks for investigating. I am not so sure anymore that Decentraleyes really breaks Weather Underground. I noticed that the graphs did not update, so I disabled add-on by add-on until the graphs got updated. If nothing changed after a reload, I enabled the add-on again. When I disabled Decentraleyes the graphs got updated, which let me believe that Decentraleyes stopped the update to work. But it can be a side effect of other add-ons being disabled. Who knows? There are too many possible culprits here!

I think you excluded the possibility that Decentraleyes is to blame. That's a very good job! If you feel like it, please close this bug report.

**Comment by Synzvato** [comment] 2017-01-27 14:14
@sphh You're welcome and thanks for the update! Since the behavior can't be reproduced, I think closing this issue is indeed justified. Feel free to re-open it if anything changes in that respect.

**Closed by Synzvato** 2017-01-27 14:14 UTC
Labels: invalid, observation

**Comment by clavelc** [comment] 2017-02-18 18:35
Hi

I'm having a problem with a site too, which only loads correctly with decentraleyes deactivated: https://www.signatureflight.com/locations/sou 

Might be a coincidence, but the site fetches data from wunderground.com as well... 

any idea?

Thanks
