### ISSUE TITLE
Include more then just scripts for local loading

### ISSUE THREAD

**Issue by beerisgood** [Synzvato/decentraleyes#183] opened 2017-07-21 08:48 UTC
Why not add stuff like fonts  (https://fonts.googleapis.com for example) and other ressources to Decentraleyes to make browsing the web faster and more privacy friendly?

**Comment by PleaseDontBanMe** [comment] 2017-08-04 13:42
By default I would say no, that stuff is dozens of Mo big, I would say if this gets implemented it should offer the possibility to download Google Fonts https://github.com/Synzvato/decentraleyes/issues/182

With an interface like uBlock Origin:

![](https://cloud.githubusercontent.com/assets/585534/24972255/cbf77306-1f88-11e7-808e-1e1ac934120f.png)

**Comment by pwd-github** [comment] 2017-09-20 09:16
I was just coming to suggest that Decentraleyes offers the CSS from fonts.googleapis.com

**Comment by meskarune** [comment] 2017-10-16 15:12
They could add the bootstrap css and fontawesome since those are so widely used. Maybe normalize.css too.

**Comment by Synzvato** [comment] 2017-11-26 05:11
@beerisgood, @pwd-github

Thanks for the suggestions everyone! Needless to say, a lot of time went into completely rewriting the legacy add-on. Now that Decentraleyes adheres to modern standards, we can shift our focus. Since this request is mostly dedicated to Google Fonts, I'm marking this as a duplicate of related issue #34.

@meskarune

> They could add the bootstrap css and fontawesome [...]. Maybe normalize.css too.

Thanks! I'm happy to say that at least Bootstrap and Font Awesome are likely candidates. Any updates regarding those two resources will be posted inside of issue #37. Feel free to upvote the proposal.

**Closed by Synzvato** 2017-11-26 05:11 UTC
