### ISSUE TITLE
Break sites with integrity implements

### ISSUE THREAD

**Issue by gloomy-ghost** [Synzvato/decentraleyes#161] opened 2017-04-23 12:54 UTC
e.g. https://report-uri.io/

```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" integrity="sha256-ivk71nXhz9nsyFDoYoGf2sbjrR9ddh+XDkCcfZxjvcM=" crossorigin="anonymous"></script>
```

```
None of the "sha256" hashes in the integrity attribute match the content of the subresource.
```

**Comment by TriMoon** [comment] 2017-04-25 16:15
Confirmed, the reason it breaks is due to the fact that decentral eyes serves a local copy

The local copy has an added header which in my test, just now, starts like:
```
/**
 * Local delivery by Decentraleyes (1.3.8).
 */
```

Now the question is what the developer(s) should do:
  1) Disable local delivery by Decental eyes for resources that have integrity info?
     - Not my choice!
  1) Recalculate the SRI to conform to the local version?
     - Is this possible without rewriting the html?
  - Decentral eyes should finally implement SRI anyway as suggested in other issue(s) IIRC 😉

**Comment by Synzvato** [comment] 2017-04-25 19:54
@gloomy-ghost Hi, thanks for reporting this! As a first step, I'll ensure perfect resource integrity with Google Hosted Libraries, since it's the most commonly used CDN. This should (very significantly) reduce page breakage. I'm currently experimenting with implementing transformers, to see if that's workable.

For now, please add ```report-uri.io``` to the domain whitelist inside the extension preferences.

@TriMoon Thanks for weighing in, but please allow me me clarify a few things here.

> The local copy has an added header [...]

This feature is not present in the experimental rewrite. Therefore it's not relevant, and it's _not_ the only reason why SRI enforcement can break pages. As odd as it may sound, it turns out that different CDNs serve different files, even when requesting a _specific_ version of a _specific_ resource.

> Recalculate the SRI to conform to the local version?

This solution is extremely high-level, and would inevitably show things down. It would mean that all sorts of actions would need to be taken before a browser is allowed to attempt to interpret a given document.

> Decentral eyes should finally implement SRI anyway as suggested in other issue(s) IIRC :wink:.

The issues you are linking to are unrelated. Using SRI attributes to detect libraries loaded from first parties or small CDN services, is not the same thing as embracing (or circumventing) such security measures.

Also, there are clear reasons as to why SRI-based look-ups have not yet been implemented. It's a fairly neat idea, but [Mozilla](https://github.com/Synzvato/decentraleyes/issues/26#issuecomment-177913922) and [W3C contributors](https://github.com/w3c/webappsec-subresource-integrity/issues/22) are struggling with possible security complications.

**Comment by TriMoon** [comment] 2017-04-28 12:32
@Synzvato , the links i gave were randomly chosen because they mentioned SRI in someway, so sorry bout them not being to the point then 🤣 
(I couldn't quickly find the one(s) requesting SRI support when i posted)

> @TriMoon; Recalculate the SRI to conform to the local version?
> @Synzvato; This solution is extremely high-level, and would inevitably slow things down. It would mean that all sorts of actions would need to be taken before a browser is allowed (to attempt) to interpret a given page.

I should have written _replace_ instead of _recalculate_ 😉 
Making it read: "_**Replace the SRI to conform to the local version?**_"
(Typos happen when you're in a hurry)

> As odd as it may sound, it turns out that different CDNs serve different files, even when requesting a specific version of a specific resource.

In cases like that it's actually a _good thing™_ that Decentral eyes dilivers the correct version IMHO...

**Comment by lilydjwg** [comment] 2017-09-26 13:04
What about shipping all the files of same version but with different hashes, so that SRI hashes can match?

**Comment by Synzvato** [comment] 2017-11-23 16:08
> I should have written [...]: "Replace the SRI to conform to the local version?"

@TriMoon Such actions would likely need to be performed synchronously, and before your browser interprets a given document. This would essentially mean executing most of the extension's logic while your browser does not yet have anything to work with. This would apply to any ```HTML``` document.

> In cases like that it's [...] _a good thing™_ that Decentral eyes dilivers the correct version [...].

I fully agree. Perhaps it would also be a good idea to asynchronously perform SRI-checks whenever Decentraleyes has no choice but to allow a request. There could be an internal index of hashes for any supported delivery networks. A warning could be shown when a file differs from everyone else's.

> What about shipping all the files of same version but with different hashes [...]?

@lilydjwg Doing so would increase the size of the extension. In my opinion, such a measure would be disproportionate, especially given the small amount of sites who currently implement SRI-hashes.

**Comment by Synzvato** [comment] 2017-11-23 16:11
I'm hereby marking this as a duplicate of related issue #16, so feel free to post any responses there.

**Closed by Synzvato** 2017-11-23 16:11 UTC

**Comment by Synzvato** [comment] 2017-12-03 15:09
I have since decided to create a new bug ([```1419459```](https://bugzilla.mozilla.org/show_bug.cgi?id=1419459)) on Mozilla's bugtracker. Upvotes are welcome.
