### ISSUE TITLE
RequestPolicy Continued breaks core features

### ISSUE THREAD

**Issue by YtvwlD** [Synzvato/decentraleyes#226] opened 2017-11-01 14:51 UTC
Today, I noticed that several files under https://ajax.googleapis.com/ajax/libs/jquery/ fail to load. I first noticed it using StackOverflow, but the issue also appears on https://decentraleyes.org/test/ .

I have Request Policy Continued and HTTPS Everywhere installed, but the issue persists if I disable both of them.

The issue goes away if I downgrade to 1.13.10 (but comes up shortly after because of the auto update to 2.0).

I'm on Firefox 56.0.

**Comment by Synzvato** [comment] 2017-11-01 18:46
Hi @YtvwlD, and thanks for getting in touch! Could you please let me know what version of RequestPolicy Continued you are using? Also, could you try disabling said extension entirely, via ```about:addons```?

**Comment by YtvwlD** [comment] 2017-11-02 11:32
So, I created a new browser profile and installed Decentraleyes (2.0), HTTPS Everywhere and RequestPolicy Continued. The test failed.
I disabled RequestPolicy Continued via `about:addons` and the test succeeded.
After re-enabling RequestPolicy Continued the test failed again.

**Comment by Synzvato** [comment] 2017-11-02 16:20
Thanks for the additional details! I'm marking this as a duplicate of related issue #208. You should be able to restore functionality on both ends, by upgrading to RequestPolicy Continued ```1.0.beta13.2```.

**Closed** 2017-11-02 16:26 UTC
Labels: duplicate, observation

**Comment by YtvwlD** [comment] 2017-11-02 16:40
This really looks like my issue, but I already have RequestPolicy Continued `1.0.beta13.2`.

**Comment by Synzvato** [comment] 2017-11-02 18:19
I was able to reproduce your problem, and have posted a possible workaround inside of issue #208.
