### ISSUE TITLE
Decentraleyes breaks Yandex Disk

### ISSUE THREAD

**Issue by dartraiden** [Synzvato/decentraleyes#117] opened 2016-08-22 19:57 UTC
Example URL: https://yadi.sk/d/buEC80xBsqe4F/15.6%20-%202010.03.01
Download button don't work with Decentraleyes enabled

**Comment by Feodor2** [comment] 2016-08-24 12:53
It also breaks mail.yandex.ru. It is something with yastatic.net, apparently they changed js files there.
How one can see what files is using. I do know fiddler, but since for some time it incompatible with new type https connections.

**Comment by Feodor2** [comment] 2016-09-09 07:10
I managed to make fiddler work. Yandex wants jquery 1.11.0
There is something with jquery substitution, it does not happen.

**Comment by Atavic** [comment] 2016-10-04 19:39
The link in the source has a string:
`/Gksoiw7sCWKl3P7-dP1d4Assx6YQzFL2hEyhZJ4tI-M=:/`

This part of the link disappears once you click on it and look at the Browser URL.

**Comment by Synzvato** [comment] 2016-10-24 10:08
@dartraiden Thanks for reporting this! It's a known problem (see issue #16). It's a browser limitation that Mozilla is currently looking into. This should be fixed after we port the add-on to ```WebExtensions```.

In the meantime, please try adding ```yadi.sk``` to your Decentraleyes domain whitelist.

**Closed by Synzvato** 2016-10-24 10:08 UTC
Labels: bug, duplicate

**Comment by dimqua** [comment] 2017-10-29 02:37
@Synzvato this bug still affect version 2.0.

**Comment by Synzvato** [comment] 2017-11-04 14:37
@dimqua Thanks for reporting this regression! Expect the very next update to fix the issue.
