### ISSUE TITLE
Some site functionality breaks on Udacity

### ISSUE THREAD

**Issue by jawz101** [Synzvato/decentraleyes#198] opened 2017-09-13 14:34 UTC
https://www.udacity.com/course/new-android-fundamentals--ud851

click on Start Free Course button on page.  Blocked

**Comment by Synzvato** [comment] 2017-09-13 15:20
Hi @jawz101, and thanks for taking the time to report this problem!

It's a known issue that occurs when sites force resource contents to be _exactly_ identical to what they expect. The real problem here is that file contents can differ between CDNs, since they are tied to matters like line ending types, or the existence of source mapping URLs. Not many sites enforce ```SRI```.

For now, I would recommend manually whitelisting the domain in question. An ```SRI```-detection mechanism is currently in the works. If all goes well, it might land before ```v2.0.0``` turns stable.

**Comment by Synzvato** [comment] 2017-09-13 15:34
I'm marking this as a duplicate of related issue #16.

**Closed by Synzvato** 2017-09-13 15:34 UTC
Labels: bug, duplicate
