### ISSUE TITLE
Decentraleyes breaks Code Academy

### ISSUE THREAD

**Issue by chinaar** [Synzvato/decentraleyes#115] opened 2016-08-10 06:13 UTC
It appears as if turning this addon on makes the login and signup boxes disappear on codeacademy.com. I have confirmed that this error does not occur in safe mode and only reproduces when decentraleyes is turned on.

**Comment by Synzvato** [comment] 2016-10-24 10:22
@chinaar Thanks for reporting this! I'm unable to replicate the issue, so it might have been fixed by changes on their end. It was likely caused by the exact same browser limitation that caused the problems mentioned in issue #16. Please let me know if you're still experiencing issues.

**Closed** 2016-10-24 10:22 UTC
Labels: bug, duplicate

**Comment by Synzvato** [comment] 2017-12-03 15:07
@chinaar I have decided to create a bug ([```1419459```](https://bugzilla.mozilla.org/show_bug.cgi?id=1419459)) on Mozilla's bugtracker. Upvotes are welcome.
