### ISSUE TITLE
Can Decentraleyes work with web fonts?

### ISSUE THREAD

**Issue by 9Morello** [Synzvato/decentraleyes#132] opened 2016-12-05 02:59 UTC
I think title says it all. Could support be added for web fonts?

**Comment by Bisaloo** [comment] 2016-12-05 11:25
See https://github.com/Synzvato/decentraleyes/issues/105 and https://github.com/Synzvato/decentraleyes/issues/77

**Comment by 9Morello** [comment] 2016-12-05 15:20
@Bisaloo oh, my bad for not looking. Thanks.

**Comment by Synzvato** [comment] 2017-01-27 10:39
For administrative purposes, I'm marking this as a duplicate of #69.

**Closed by Synzvato** 2017-01-27 10:39 UTC
Labels: duplicate, question
