### ISSUE TITLE
Add site-specific statistics to the user interface

### ISSUE THREAD

**Issue by klundberg** [Synzvato/decentraleyes#213] opened 2017-10-17 16:02 UTC
I'd love to see statistics for the current site I'm looking at, to see how many resources were requested that Decentraleyes both did and did not provide, and possibly a detailed list of each resource in these buckets in some advanced screen. This would give users a better sense of what the addon is doing on a per-webpage basis, and it could also help reveal potential candidates for resources that decentraleyes could provide in the future.

An additional or alternative enhancement to this could also be to add more detailed statistics to the total resource count that already exists. I'd love to see a breakdown of which domains (or even which specific resources) make up that total count.

**Comment by Synzvato** [comment] 2017-10-20 22:05
Hi @klundberg, and thanks for the suggestions! The graphical user interface will definitely be receiving more features, and polish, as soon as the dust settles, so your feedback is more than welcome.

> I'd love [...] to see how many resources [...] Decentraleyes both did and did not provide [...]. I'd love to see a breakdown of which domains (or even which specific resources) make up that total count.

Even when Decentraleyes does not directly provide a resource, it still helps out by stripping sensitive data (e.g. what page you are on) from the outgoing request. This should most definitely be visualized.

> This would give users a better sense of what the addon is doing on a per-webpage basis, and it could also help reveal potential candidates for resources that decentraleyes could provide in the future.

I agree that it might give power users some insight into what they are most dependent on, but I see no real need for it yet. That said, this could become interesting once users are able to add non-default library packages. It would allow users to save space, by finding out what bundles are most helpful to them.

User statistics will not be used to reveal candidates, as Decentraleyes doesn't collect user data. Crawling the web has proven to be a very accurate way, of gathering JavaScript library usage statistics.

I'm marking this as a duplicate of related issue #145, so please post any replies there. Thanks again!

**Closed** 2017-10-20 22:06 UTC
Labels: duplicate, request
