### ISSUE TITLE
Breaks Imgur-pages with GIFV content

### ISSUE THREAD

**Issue by ibrokemypie** [Synzvato/decentraleyes#154] opened 2017-03-18 01:41 UTC
When loading a .gifv on imgur it breaks with 
```
imgur.js:320 Uncaught TypeError: _.templates.galleryimage.favoriteBar is not a function
    at d.appendFavoriteBar (imgur.js:320)
    at Object.b [as success] (lodash.min.js:10)
    at j (jquery.min.js.dec:2)
    at Object.fireWith [as resolveWith] (jquery.min.js.dec:2)
    at x (jquery.min.js.dec:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js.dec:4)
    at XMLHttpRequest.d (raven-3.7.0.js:379)
appendFavoriteBar	@	imgur.js:320
b	@	lodash.min.js:10
j	@	jquery.min.js.dec:2
fireWith	@	jquery.min.js.dec:2
x	@	jquery.min.js.dec:4
(anonymous)	@	jquery.min.js.dec:4
d	@	raven-3.7.0.js:379

```

**Comment by Bisaloo** [comment] 2017-03-18 06:56
Do you have a test URL? I tested with this (among others) and it works fine:

https://i.imgur.com/4URK6ca.gifv

**Comment by Synzvato** [comment] 2017-03-20 00:32
@Bisaloo I am also unable to reproduce the bug. @ibrokemypie I'll be closing this issue, but feel free to re-open it once you have some additional details for us. That's when we can start looking into this.

**Closed by Synzvato** 2017-03-20 00:32 UTC
