### ISSUE TITLE
Add the ability to re-enable network prediction

### ISSUE THREAD

**Issue by ghost** [Synzvato/decentraleyes#196] opened 2017-09-09 20:03 UTC
Decentraleyes changing these internal Firefox preferences:
```
-network.dns.disablePrefetch;true
-network.http.speculative-parallel-limit;0
-network.predictor.enable-prefetch;true
-network.prefetch-next;false
```
in about:config without my permission and without my knowledge,
Default preferences are:
```
-network.dns.disablePrefetch;false
-network.http.speculative-parallel-limit;6
-network.predictor.enable-prefetch;false
-network.prefetch-next;true
```

I also don't have ability to control (enable/disable) this "feature".

I'm using Decentraleyes 2.0.0beta2 + Firefox Nightly 57.0a1.

Please provide ability to control (enable/disable) this "feature" and some information after installing this extension.

**Comment by Synzvato** [comment] 2017-09-09 21:50
Hi, and thanks for sharing your concerns. Allow me to clear up some of the confusion.

> Decentraleyes changing [...] about:config without my permission [...].

Upon installing the extension, you've been explicitly told that Decentraleyes requires your permission to read and modify privacy related settings. So let me stress that the extension is not doing anything it does not have your permission for. In addition, the code is completely open source, and open for scrutiny.

![image](https://user-images.githubusercontent.com/2366020/30243756-8d0375ac-957e-11e7-8f8e-aa85acc5b397.png)
_Decentraleyes requesting permissions during installation._

---

> I also don't have ability to control (enable/disable) this "feature".

In most cases, you absolutely do not want to disable this protection measure. It has been put in place to combat CDN request leakage (see issue #188). Uninstalling, or simply disabling, Decentraleyes will revert all settings back to their original values. This means that the measure does not pollute your profile.

Extensions such as uBlock Origin take the exact same measures to prevent undesired traffic. However, should you plan on using this extension for reasons other than privacy protection, and should you not care about request leakage, you might be glad to hear that this measure will be made optional in the future.

**Comment by Synzvato** [comment] 2017-09-09 22:24
I'm marking this as a duplicate of closely related issue #157.

**Closed** 2017-09-09 22:25 UTC
Labels: duplicate, request

**Comment by SMed79** [comment] 2017-09-10 01:45
@ghost The old extensions had more power, but users were not informed before the installation.

Read this blog post https://palant.de/2017/08/05/revisiting-permission-prompt-for-firefox-extensions
