### ISSUE TITLE
Allow users to subscribe to external bundles

### ISSUE THREAD

**Issue by ghost** [Synzvato/decentraleyes#182] opened 2017-07-04 08:08 UTC
The idea is to use a similar platform to uBlockOrigin:

![](https://cloud.githubusercontent.com/assets/585534/24972255/cbf77306-1f88-11e7-808e-1e1ac934120f.png)

The idea is that you can group lists of resources that can be loaded from there. So advanced users who want to load all Google fonts will simply have to choose that from the list and wait until they're downloaded (preferably from a Github repo since github.com isn't blocked anywhere on the world).

**Comment by heubergen** [comment] 2017-07-04 08:11
I would support this, but only with low priority. The first priority should be the WebExtensions Port :)

**Comment by Synzvato** [comment] 2017-11-26 15:00
Thank you for sharing your thoughts on this! For administrative purposes, I will be marking this issue as a duplicate of closely related issue #6. So, feel free to continue this conversation there. Thanks again!

**Closed by Synzvato** 2017-11-26 15:00 UTC
