### ISSUE TITLE
Decentraleyes breaks 10FastFingers

### ISSUE THREAD

**Issue by onodera-punpun** [Synzvato/decentraleyes#241] opened 2017-12-18 20:36 UTC
With Decentraleyes enabled the 10fastfingers typing test (https://10fastfingers.com/typing-test/english) stops working.

**Comment by Synzvato** [comment] 2017-12-19 15:30
This is a known issue (see #16). The website's security settings keep Decentraleyes from injecting any libraries into the page. For now, adding the domain ```10fastfingers.com``` to the whitelist should solve your problem. A permanent solution is currently [being discussed](https://github.com/Synzvato/decentraleyes/issues/16#issuecomment-348766926). Please do let me know if this helps!

**Comment by Synzvato** [comment] 2017-12-19 15:31
I'm marking this as a duplicate of related issue #16.

**Closed** 2017-12-19 15:32 UTC
Labels: bug, duplicate
